version: '3.6'
services:
  mysql:
    image: 'mysql:5.7'
    ports:
     - '3306:3306'
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
  phpadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '8000:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    depends_on: 
      - mysql